version: '3.8'

networks:
  backend-network:
    driver: bridge

services:
  ########################
  #  API Gateway Service #
  ########################
  api-gateway:
    build:
      context: ./API-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - trading-service
      - account-service
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://admin:hw445Rl1pEAXqhti@cluster-1-shard-00-00.rylgk.mongodb.net:27017,cluster-1-shard-00-01.rylgk.mongodb.net:27017,cluster-1-shard-00-02.rylgk.mongodb.net:27017/user-database?replicaSet=atlas-vamz5w-shard-0&authSource=admin&retryWrites=true&w=majority&ssl=false"
#    dns:
#      - 8.8.8.8
#      - 1.1.1.1

  ######################
  #  User-Service      #
  ######################
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    expose:
      - "8081"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://admin:hw445Rl1pEAXqhti@cluster-1-shard-00-00.rylgk.mongodb.net:27017,cluster-1-shard-00-01.rylgk.mongodb.net:27017,cluster-1-shard-00-02.rylgk.mongodb.net:27017/user-database?ssl=true&replicaSet=atlas-vamz5w-shard-0&authSource=admin&retryWrites=true&w=majority"
#    dns:
#      - 8.8.8.8
#      - 1.1.1.1

  ######################
  #  Account-Service   #
  ######################
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    expose:
      - "8083"
  #    dns:
  #      - 8.8.8.8
  #      - 1.1.1.1

  ######################
  #  Trading-Service   #
  ######################
  trading-service:
    build:
      context: ./trading-service
      dockerfile: Dockerfile
    container_name: trading-service
    expose:
      - "8084"
#    dns:
#      - 8.8.8.8
#      - 1.1.1.1
